// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Commission struct {
	ID        string `json:"id"`
	User      *User  `json:"user"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	Completed bool   `json:"completed"`
	CreatedAt string `json:"createdAt"`
}

type Domain struct {
	ID        string `json:"id"`
	User      *User  `json:"user"`
	Name      string `json:"name"`
	Completed bool   `json:"completed"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type RandomQuest struct {
	ID        string   `json:"id"`
	User      *User    `json:"user"`
	Name      string   `json:"name"`
	Longitude *float64 `json:"longitude,omitempty"`
	Latitude  *float64 `json:"latitude,omitempty"`
	Completed bool     `json:"completed"`
	CreatedAt string   `json:"createdAt"`
}

type User struct {
	ID           string         `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	CreatedAt    string         `json:"createdAt"`
	Commissions  []*Commission  `json:"commissions"`
	Domains      []*Domain      `json:"domains"`
	WeeklyBosses []*WeeklyBoss  `json:"weeklyBosses"`
	RandomQuests []*RandomQuest `json:"randomQuests"`
}

type WeeklyBoss struct {
	ID        string `json:"id"`
	User      *User  `json:"user"`
	Name      string `json:"name"`
	Completed bool   `json:"completed"`
	CreatedAt string `json:"createdAt"`
}
